### PR TITLE
Rewrote Starter in V

### PR DESCRIPTION
**Pull request by pavi2410**
TODO:
- [x] Icons
- [x] Embed adb
- [x] Write GitHub Actions workflow
- [x] Make a release workflow (https://github.com/vlang/v/blob/master/.github/workflows/binary_artifact.yml)
- [ ] Write a GUI

### CODE REVIEW

**Review by bartmathijssen — COMMENTED** [review]
I don't have any experience using the V programming language. But there are still things I would like to point out. 

It looks like you have started the project from scratch, which means you also removed some files that shouldn't be removed. I am talking about the `.gitignore` and `.github/FUNDING.yml` for example.

Something else I would like to point out is the naming of the main file. I'm not sure what the standard naming convention is in the V programming language, but maybe the main file should be renamed from `KodularStarter.v` to something more generic, like `main.v`.

**Comment by pavi2410** [comment]
I have restored the `.github/FUNDING.yml` file. `.gitignore` is not needed because it was for Python and PyCharm stuff, none of which are needed now.

There's no point of renaming the file to a generic name because this is not a generic program :)

**Comment by pavi2410** [comment]
Tested this on macOS. Works with Firefox. Safari blocks the request even though CORS headers are sent.

**Comment by pavi2410** [comment]
Thanks, @Sander0542! The release workflow is done.

**Pull request merged**
